version: '3'
services:
  audit:
    image: 'uazlibraries/ace-audit-manager:1.14.1'
    restart: always
    tty: true
    ports:
      - "8080:8080"
    environment:
      - DB_DATABASE=${ACE_AM_DATABASE:-aceamdb}
      - DB_HOST=${ACE_AMDB_HOST:-db-host}
      - DB_PORT=${ACE_AMDB_PORT:-3306}
      - DB_USER=${ACE_AMDBA_USER:-aceam}
      - DB_PASSWORD=${ACE_AMDBA_PASSWORD:-ace}
      - BOOTSTRAP_SLEEP=${ACE_AM_BOOTSTRAP_SLEEP:-45}
    volumes:
      - ${ACE_AUDIT_SHARES:-/mnt}:/mnt
